Repository wonderflow-bv/design, pull requests merged in 2021-11, with the labels that each got.

#214 feat: add Range doc
  package-lock.json
  package.json
  pages/develop/components/range.mdx
  src/navigation.ts
Labels: feature

#220 feat: add ButtonsGroup doc
  package-lock.json
  package.json
  pages/develop/components/button.mdx
Labels: feature

#222 feat: add MenuButton
  package-lock.json
  package.json
  pages/develop/components/menu-button.mdx
  src/styles/app.css
Labels: feature

#229 feat: refactoring components navigation
  next.config.js
  pages/components/buttons/button.mdx
  pages/components/buttons/icon-button.mdx
  pages/components/buttons/split-button.mdx
  pages/components/buttons/toggle-button.mdx
  pages/components/dialogs/dropdown.mdx
  pages/components/dialogs/info-state.mdx
  pages/components/dialogs/modal.mdx
  pages/components/dialogs/snackbar.mdx
  pages/components/dialogs/tooltip.mdx
  pages/components/inputs/select.mdx
  pages/components/inputs/selection-controls.mdx
  pages/components/inputs/slider.mdx
  pages/components/inputs/textfield.mdx
  pages/components/layouts/container.mdx
  pages/components/layouts/separator.mdx
  pages/components/loading/circular-progress.mdx
  pages/components/loading/linear-progress.mdx
  pages/components/loading/skeleton-block.mdx
  pages/components/loading/spinner.mdx
  pages/components/other/avatar.mdx
  pages/components/other/card.mdx
  pages/components/other/chip.mdx
  pages/components/other/disclosure.mdx
  pages/components/other/elevator.mdx
  pages/components/other/icon.mdx
  pages/components/other/star-meter.mdx
  pages/components/other/tab.mdx
  pages/components/other/theme-switch.mdx
  pages/components/typography/clamp-text.mdx
  pages/components/typography/list.mdx
  pages/components/typography/prose.mdx
  pages/components/typography/text.mdx
  pages/components/typography/title.mdx
  redirects.js
  src/components/tree/tree.module.css
  src/navigation.ts
Labels: enhancement

#230 feat: add Grid doc
  next.config.js
  package-lock.json
  package.json
  pages/components/layouts/grid.mdx
  src/navigation.ts
Labels: feature

#231 feat: add component overview page
  package-lock.json
  package.json
  pages/components/layouts/grid.mdx
  pages/components/overview.mdx
  public/develop/covers/buttons.png
  public/develop/covers/dialogs.png
  public/develop/covers/inputs.png
  public/develop/covers/layouts.png
  public/develop/covers/loading.png
  public/develop/covers/other.png
  public/develop/covers/typography.png
  src/components/quicklinks/quicklinks.tsx
  src/navigation.ts
Labels: feature

#242 feat: add Pagination
  next.config.js
  package-lock.json
  package.json
  pages/components/actions/button.mdx
  pages/components/actions/disclosure.mdx
  pages/components/actions/icon-button.mdx
  pages/components/actions/split-button.mdx
  pages/components/actions/toggle-button.mdx
  pages/components/navigation/pagination.mdx
  pages/components/navigation/tab.mdx
  pages/components/overview.mdx
  public/develop/covers/navigation-dark.png
  public/develop/covers/navigation-light.png
  src/components/tree/tree.tsx
  src/navigation.ts
Labels: feature

#243 feat: add input group
  package-lock.json
  package.json
  pages/components/inputs/input-group.mdx
  src/navigation.ts
Labels: feature

#246 feat: add table doc
  package-lock.json
  package.json
  pages/components/layouts/table.mdx
  pages/components/overview.mdx
  src/navigation.ts
Labels: documentation
